### ISSUE TITLE
I need help with VNC Tiger

### ISSUE THREAD

**Issue by Rafonsi** [ahuang-cs/CISC191#20]
When I was installing IntellJ to the instance my program crashed. now whenever I want to connect my instace to vnc tiger I get an error message saying "Conection refused (10061.) Does anyone know how to fix this? The professor tried to help but I think he gave up on me because he's not answering anymore. I've been struggling with this since sunday morning

**Comment by ahuang-cs** [comment]
I sent out an announcement yesterday about abandoning AWS if you haven't figured it out yet. Just install git and maven on your own box and develop on whatever you successfully used in the past. You will just need git to checkout code and maven to push your jars. See my announcement for details, at the bottom of https://sdccd.instructure.com/courses/2382940/discussion_topics/14089364.

**Comment by Rafonsi** [comment]
sorry I missed the announcent. I will use JGrasp because that what I used on CISC190

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
